<?php
/**
 * @category	design
 * @package		Iparcel_All
 * @author		Bobby Burden <bburden@i-parcel.com>
 * @class		Mage_Core_Block_Template
 */
?>
<div id="starting">
<p>Starting catalog synchronization</p>
</div>
<div id="sync">
<p><span>0</span> items from <span>0</span> uploaded</p>
</div>
<div id="end">
<p><span>0</span> items from <span>0</span> successfully uploaded</p>
<p>There was <span>0</span> errors when uploading catalog</p>
</div>
<script type="text/javascript">
var sync = new iparcelSync.sync('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/iparcel_sync_ajax/catalog') ?>?isAjax=true', <?php echo Mage::getStoreConfig('catalog_mapping/upload/step'); ?>);
</script>
