<?php
/**
 * @category    design
 * @package     Iparcel_All
 * @author      Bobby Burden <bburden@i-parcel.com>
 * @class       Mage_Core_Block_Template
 */
$initUrl = Mage::helper('adminhtml')->getUrl('adminhtml/iparcel_sync_ajax/catalogJsonInit');
$uploadUrl = Mage::helper('adminhtml')->getUrl('adminhtml/iparcel_sync_ajax/catalogJsonUpload');
?>
<?php echo $this->getStartButton(); ?>

<div id="message">
<p>Click "Start" to begin the Catalog Sync</p>
</div>
<textarea id="log-area" wrap="off"></textarea>
<script type="text/javascript">
jQuery(document).ready(function() {
    window.catalogSync = new iparcelSync('<?php echo $initUrl ?>', '<?php echo $uploadUrl ?>', <?php echo Mage::getStoreConfig('catalog_mapping/upload/step'); ?>, jQuery('.middle div button')[0]);
})
</script>
