<?php
/**
 * @category	design
 * @package		Iparcel_All
 * @author		Bobby Burden <bburden@i-parcel.com>
 * @class		Mage_Core_Block_Template
 */
?>
<div id="starting">
<p>Starting checking items</p>
</div>
<div id="sync">
<p><span>0</span> items from <span>0</span> checked</p>
</div>
<div id="end">
<p><span>0</span> items from <span>0</span> successfully checked</p>
<p>There was <span>0</span> errors when checking items</p>
</div>
<script type="text/javascript">
var sync = new iparcelSync.sync('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/iparcel_sync_ajax/checkitems') ?>?isAjax=true', 1);
</script>
