<?php $_item = $this->getItem() ?>
<tr class="border">
    <td><?php echo $this->getColumnHtml($_item, 'name') ?></td>
    <td><?php echo $this->getColumnHtml($_item, 'qty') ?></td>

    <td class="last a-center">
        <?php if ($this->canShipPartiallyItem()): ?>
            <input type="text" class="input-text qty-item" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="0" />
        <?php else: ?>
            <?php echo $_item->getQty()*1 ?>
        <?php endif; ?>
    </td>
    <?php if (!$this->canShipPartiallyItem()): ?>
        <td class="a-center last">
            <input type="hidden" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="0" />
            <input type="checkbox" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="<?php echo $_item->getQty()*1 ?>" checked />
        </td>
    <?php endif; ?>
</tr>
