<form id="edit_form" method="post" action="<?php echo $this->getSaveUrl() ?>">
    <?php echo $this->getBlockHtml('formkey')?>
    <input type="hidden" name="shipment[info][shipment_id]" value="<?php echo $this->getShipment()->getId() ?>" />

    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Items to Split into Seperate Shipment') ?></h4>
        </div>
    </div>

    <div id="ship_items_container">
        <?php echo $this->getItemsHtml() ?>
    </div>
</form>
<?php echo $this->getChildHtml('shipment_packaging') ?>
<script type="text/javascript">
    //<![CDATA[
    editForm = new varienForm('edit_form');
    //]]>
</script>
