<div class="grid np">
    <div class="hor-scroll">
        <table cellspacing="0" class="data order-tables">
            <col />
            <col width="1" />
            <col width="1" />
            <?php if (!$this->canShipPartiallyItem()): ?>
                <col width="20" />
            <?php endif; ?>
            <thead>
            <tr class="headings">
                <th><?php echo $this->helper('sales')->__('Product') ?></th>
                <th class="a-center"><?php echo $this->helper('sales')->__('Qty') ?></th>
                <th<?php if ($this->isShipmentRegular()): ?> class="last"<?php endif; ?>><span class="nobr"><?php echo $this->helper('iplogistics')->__('Qty to Split') ?></span></th>
            </tr>
            </thead>
            <?php $_items = $this->getShipment()->getAllItems() ?>
            <?php $_i=0;foreach ($_items as $_item): if ($_item->getOrderItem()->getIsVirtual() || $_item->getOrderItem()->getParentItem()): continue; endif; $_i++ ?>
                <tbody class="<?php echo $_i%2?'odd':'even' ?>">
                <?php echo $this->getItemHtml($_item) ?>
                <?php echo $this->getItemExtraInfoHtml($_item->getOrderItem()) ?>
                </tbody>
            <?php endforeach; ?>
        </table>
    </div>
</div>
<br />

<div class="box-right entry-edit">
    <div class="order-totals">
        <div class="order-totals-bottom">
            <div class="a-right">
                <?php echo $this->getChildHtml('submit_button') ?>
            </div>
        </div>
    </div>
</div>

<div class="clear"></div>
<script type="text/javascript">
    //<![CDATA[
    function submitShipment(btn) {

        if (!validQtyItems()) {
            return;
        }

        if(editForm.submit()) {
            disableElements('submit-button');
        }
    }

    function validQtyItems() {
        var valid = true;
        var errorMessage = '<?php echo Mage::helper('core')->jsQuoteEscape($this->helper('iplogistics')->__('Invalid value(s) for Qty to Split')) ?>';
        $$('.qty-item').each(function(item) {
            var val = parseFloat(item.value);
            if (isNaN(val) || val < 0) {
                valid = false;
                alert(errorMessage);
                throw $break;
            }
        });
        return valid;
    }
    //]]>
</script>
